apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hostname-deployment
spec:
  selector:
    matchLabels:
      app: node-hostname
  replicas: 2
  template:
    metadata:
      labels:
        app: node-hostname
    spec:
      containers:
      - name: node-hostname 
        image: thadiggitystank/node-hostname:latest
        ports:
        - containerPort: 80
        resources: 
          limits:
            cpu: 100m
            memory: 100mi
---

apiVersion: v1
kind: Service
metadata:
  name: node-hostname-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: robbie-node.k8s.alliedelec.com
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - port: 80 
    name: http
    targetPort: 80 