apiVersion: v1
kind: Service
metadata:
  name: node-hostname-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: robbie.k8s.alliedelec.com
spec:
  type: LoadBalancer
  selector:
    app: node-hostname
  ports:
  - port: 80 
    name: http
    targetPort: 80 

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-hostname
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: node-hostname
    spec:
      containers:
      - name: node-hostname 
        image: quay.io/allied-electronics/node-hostname:rolling-upgrade
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
      imagePullSecrets:
        - name: allied-private-registry