apiVersion: v1
kind: Service
metadata:
  name: node-hostname-lb
  namespace: dev
  annotations:
    external-dns.alpha.kubernetes.io/hostname: robbie.k8s.alliedelec.com
spec:
  type: LoadBalancer
  selector:
    app: node-hostname
  ports:
  - port: 80 
    name: http
    targetPort: 80 

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dev
  name: node-hostname-deployment
spec:
  template:
    metadata:
      labels:
        app: node-hostname
    spec:
      containers:
      - name: node-hostname 
        image: thadiggitystank/node-hostname:latest
        ports:
        - containerPort: 80